services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    working_dir: /app
    env_file:
      - .env.production
    networks:
      - killmaker.net
    restart: always

networks:
  killmaker.net:
    name: killmaker.net
    external: true