services:
  killmaker:
    container_name: home
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app
    env_file:
      - .env.development
    networks:
      - deathmatch.net
    restart: always

networks:
  deathmatch.net:
    name: deathmatch.net
    external: true
