services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    volumes:
      - .:/app
      - /app/node_modules
      - /app/engine
    working_dir: /app
    env_file:
      - .env.development
    networks:
      - killmaker.net
    restart: always
    ports:
      - 3000:3000

networks:
  killmaker.net:
    name: killmaker.net
    external: true
